import { glob, mkdir, readFile, writeFile } from "node:fs/promises";
import { validateConnectorManifest, type ConnectorManifest } from "../packages/connector-manifest/src/index.js";

/**
 * Builds the browsable connector catalog from the manifests themselves, so the
 * catalog cannot describe a connector differently from how the connector
 * describes itself. Every entry shows its bypass statement, because a catalog
 * that lists only capabilities teaches people to assume coverage they do not have.
 */
const paths: string[] = [];
for await (const entry of glob("packages/*/connector.manifest.json")) paths.push(entry);
paths.sort();

const manifests: ConnectorManifest[] = [];
for (const path of paths) {
  const result = validateConnectorManifest(JSON.parse(await readFile(path, "utf8")));
  if (!result.valid) {
    console.error(`Refusing to build a catalog from an invalid manifest: ${path}`);
    for (const issue of result.issues) console.error(`  ${issue.path}: ${issue.message}`);
    process.exit(1);
  }
  manifests.push(result.manifest);
}

const LEVELS = ["isolate", "guard", "govern", "observe"] as const;
const LEVEL_MEANING: Record<string, string> = {
  isolate: "Owns the network path or credential and refuses access without grant consumption.",
  guard: "Consumes a grant immediately before invoking a handler. Strong only if the raw handler stays private.",
  govern: "Connects identity, registry, review, audit, and incident systems.",
  observe: "Reports what would have been decided. No execution control."
};

const markdown: string[] = [
  "# Connector catalog",
  "",
  "<!-- Generated by scripts/build-catalog.ts from packages/*/connector.manifest.json. Do not edit by hand. -->",
  "",
  `${manifests.length} connectors. Every entry states what it does **not** protect, because a catalog that lists only capabilities teaches people to assume coverage they do not have.`,
  "",
  "| Connector | Level | Tier | Setup | Protects |",
  "|---|---|---:|---:|---|"
];

for (const level of LEVELS) {
  for (const manifest of manifests.filter((item) => item.level === level)) {
    markdown.push(`| [\`${manifest.name}\`](#${anchor(manifest.name)}) | ${manifest.level} | ${manifest.requires.minimumTier} | ${manifest.setup.steps} steps | ${manifest.protects} |`);
  }
}

markdown.push("", "## Levels", "");
for (const level of LEVELS) markdown.push(`- **${level}** — ${LEVEL_MEANING[level]}`);
markdown.push("", "Tier is the lowest [adoption tier](../README.md#how-much-does-this-cost-to-adopt) at which the connector does something useful.", "");

for (const level of LEVELS) {
  const group = manifests.filter((item) => item.level === level);
  if (group.length === 0) continue;
  markdown.push(`## ${level[0]!.toUpperCase()}${level.slice(1)} connectors`, "");
  for (const manifest of group) {
    markdown.push(
      `### \`${manifest.name}\``, "",
      manifest.summary, "",
      `**Protects.** ${manifest.protects}`, "",
      "**Does not protect.**",
      ...manifest.bypass.map((item) => `- ${item}`), "",
      `**Requires.** ${requirements(manifest)}`, "",
      `**Setup.** ${manifest.setup.steps} steps, ${manifest.setup.requiredSettings} required settings${manifest.setup.presetName ? `, preset \`${manifest.setup.presetName}\`` : ""}.`, "",
      "**Backed by these negative tests.**",
      ...manifest.negativeTests.map((item) => `- ${item}`), ""
    );
  }
}

markdown.push("---", "", "Contributing a connector? Start with the [manifest format](integrations.md#connector-manifest) and run the [conformance suite](integrations.md#adapter-conformance) against your adapter.", "");

await mkdir(new URL("../docs/", import.meta.url), { recursive: true });
await writeFile(new URL("../docs/catalog.md", import.meta.url), markdown.join("\n"));
// No timestamp: a generated artifact that changes on every run cannot be
// diffed for drift, and git already records when it last changed.
await writeFile(new URL("../docs/api/catalog.json", import.meta.url), `${JSON.stringify({ connectors: manifests }, null, 2)}\n`);
console.log(JSON.stringify({ ok: true, connectors: manifests.length, byLevel: Object.fromEntries(LEVELS.map((level) => [level, manifests.filter((item) => item.level === level).length])) }, null, 2));

function requirements(manifest: ConnectorManifest): string {
  const needs = [
    manifest.requires.providerKey ? "a provider key" : null,
    manifest.requires.redis ? "Redis" : null,
    manifest.requires.postgres ? "PostgreSQL" : null
  ].filter(Boolean);
  return needs.length ? needs.join(", ") : "nothing beyond ActionGate itself";
}

function anchor(name: string): string {
  return name.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
}
