import { readFile, writeFile } from "node:fs/promises";

/**
 * Generates a typed client from the API description, so the client cannot drift
 * from the documented contract. Regenerate with `pnpm api:generate && pnpm client:generate`.
 */
interface Operation { operationId: string; summary?: string; parameters?: { name: string; in: string; required?: boolean }[]; requestBody?: unknown; security?: unknown[] }

const document = JSON.parse(await readFile(new URL("../docs/api/openapi.json", import.meta.url), "utf8")) as {
  info: { version: string };
  paths: Record<string, Record<string, Operation>>;
};

const methods: string[] = [];
for (const [path, operations] of Object.entries(document.paths)) {
  for (const [verb, operation] of Object.entries(operations)) {
    const pathParams = (operation.parameters ?? []).filter((parameter) => parameter.in === "path");
    const queryParams = (operation.parameters ?? []).filter((parameter) => parameter.in === "query");
    const args: string[] = pathParams.map((parameter) => `${parameter.name}: string`);
    if (operation.requestBody) args.push("body: unknown");
    if (queryParams.length) args.push(`query?: { ${queryParams.map((parameter) => `${parameter.name}?: string`).join("; ")} }`);

    const template = path.replace(/\{([A-Za-z0-9_]+)\}/g, (_, name: string) => `\${encodeURIComponent(${name})}`);
    const hasQuery = queryParams.length > 0;
    methods.push(`  /** ${operation.summary ?? operation.operationId} */
  async ${operation.operationId}(${args.join(", ")}): Promise<ApiResult> {
    return this.request("${verb.toUpperCase()}", \`${template}\`${hasQuery ? ", query" : ", undefined"}${operation.requestBody ? ", body" : ""});
  }`);
  }
}

const source = `// Generated by scripts/generate-client.ts from docs/api/openapi.json.
// Do not edit by hand: regenerate with \`pnpm api:generate && pnpm client:generate\`.
// API version ${document.info.version}.

export interface ApiResult<T = unknown> {
  status: number;
  ok: boolean;
  data: T;
}

export interface GeneratedClientOptions {
  baseUrl: string;
  apiKey: string;
  fetch?: typeof globalThis.fetch;
}

export class ActionGateApiClient {
  static readonly apiVersion = "${document.info.version}";
  private readonly fetcher: typeof globalThis.fetch;

  constructor(private readonly options: GeneratedClientOptions) {
    this.fetcher = options.fetch ?? globalThis.fetch;
  }

${methods.join("\n\n")}

  private async request(method: string, path: string, query?: Record<string, string | undefined>, body?: unknown): Promise<ApiResult> {
    const url = new URL(path.replace(/^\\//, ""), \`\${this.options.baseUrl.replace(/\\/$/, "")}/\`);
    for (const [key, value] of Object.entries(query ?? {})) if (value !== undefined) url.searchParams.set(key, value);
    const response = await this.fetcher(url, {
      method,
      headers: {
        Authorization: \`Bearer \${this.options.apiKey}\`,
        Accept: "application/json",
        ...(body === undefined ? {} : { "Content-Type": "application/json" })
      },
      ...(body === undefined ? {} : { body: JSON.stringify(body) })
    });
    const text = await response.text();
    let data: unknown = text;
    try { data = text ? JSON.parse(text) : null; } catch { /* keep the raw text */ }
    return { status: response.status, ok: response.ok, data };
  }
}
`;

await writeFile(new URL("../packages/sdk-js/src/generated/client.ts", import.meta.url), source);
console.log(JSON.stringify({ ok: true, apiVersion: document.info.version, operations: methods.length }, null, 2));
