import { readFile, writeFile } from "node:fs/promises";
import { actionBindingFingerprint, canonicalJson } from "@actiongate/core";

/**
 * Records the TypeScript outputs the Python suite must reproduce.
 *
 * Kept as a generated artifact rather than hand-written values so the
 * expectations always come from the reference implementation, and CI diffs it.
 */
const path = new URL("../fixtures/conformance/cross-language.json", import.meta.url);
const fixtures = JSON.parse(await readFile(path, "utf8")) as {
  canonicalJson: { name: string; value: unknown; expected: string }[];
  fingerprints: { name: string; binding: Record<string, unknown>; policyVersion: string }[];
};

const recorded = {
  note: "Generated by scripts/record-conformance.ts from the TypeScript implementation. The Python suite must reproduce every value.",
  canonicalJson: Object.fromEntries(fixtures.canonicalJson.map((item) => [item.name, canonicalJson(item.value)])),
  fingerprints: Object.fromEntries(fixtures.fingerprints.map((item) => [item.name, actionBindingFingerprint(item.binding as never, item.policyVersion)]))
};

await writeFile(new URL("../fixtures/conformance/expected.json", import.meta.url), `${JSON.stringify(recorded, null, 2)}\n`);
console.log(JSON.stringify({ ok: true, canonicalJson: Object.keys(recorded.canonicalJson).length, fingerprints: Object.keys(recorded.fingerprints).length }, null, 2));
